import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-red-900">Instagram Clone</h1>
    </div>
  );
}
